# Generated by Django 3.0.3 on 2020-03-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nb_players_max',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
