# Generated by Django 3.0.3 on 2020-03-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0002_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposition.Proposition'),
        ),
        migrations.AlterField(
            model_name='play',
            name='score',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
