# Generated by Django 3.0.3 on 2020-03-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_training', models.DateField(verbose_name='Date')),
                ('hour_training', models.TimeField(verbose_name='Hour')),
                ('type_training', models.CharField(max_length=300, verbose_name='Type')),
                ('team_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Team')),
            ],
        ),
    ]
